version: '3'
services:
  backend:
    platform: linux/amd64
    build:
      context: ./tanititourism
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - '8080:8080'
  frontend:
    platform: linux/amd64
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend

