DROP TABLE IF EXISTS do_type;
CREATE TABLE `do_type` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `type_name` VARCHAR(255) UNIQUE
);

DROP TABLE IF EXISTS stay_type;
CREATE TABLE `stay_type` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `type_name` VARCHAR(255) UNIQUE
); 

DROP TABLE IF EXISTS dine_type;
CREATE TABLE `dine_type` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `type_name` VARCHAR(255) UNIQUE
);

DROP TABLE IF EXISTS regions;
CREATE TABLE `regions` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) UNIQUE
);

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    role ENUM('ADMIN') NOT NULL
	
);